#!/usr/bin/env bash
#Write a Bash script that displays the content of the file '/etc/passwd'
#displays username
#displays user id
#displays Home directory path for the user

le IFS= read -r line
do
		echo "$line" | cut -f 1,3,6 -d ':'
	done < "/etc/passwd"
