#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
count=0
while [$count -lt 10] 
do	
	echo "Best School"
if [$count -et 9]
do
	echo "Best School\n"
	"Hi"
done.
