#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration
#Displays Best School and then Hi on a new line.

count=0

while [ $count -lt 10 ]  
do
	if [ $count -eq 9 ]
	then 
		echo -e "$count\nHi"
	fi
	echo "Best School"
	(( count++ ))
done.
